import { sidebar } from 'vuepress-theme-hope'

export default sidebar({
  sidebar: 'heading',
  '/md/frontend': [
    '',
    {
      text: '前端',
      children: [
        {
          text: 'HTML 笔记',
          collapsible: true,
          prefix: 'html/',
          children: [
            { text: '一、HTML简介', link: 'html01.md' },
            { text: '二、基础知识', link: 'html02.md' },
            { text: '三、HTML5新特性', link: 'html03.md' },
            { text: '四、实践和调试', link: 'html04.md' },
          ],
        },
        {
          text: 'CSS 笔记',
          prefix: 'css/',
          collapsible: true,
          children: [
            { text: '一、CSS简介', link: 'css01.md' },
            { text: '二、基础知识', link: 'css02.md' },
            { text: '三、选择器', link: 'css03.md' },
            { text: '四、盒模型', link: 'css04.md' },
            { text: '五、页面布局', link: 'css05.md' },
            { text: '六、进阶知识', link: 'css06.md' },
            { text: '七、响应式设计', link: 'css07.md' },
            { text: '八、最佳实践', link: 'css08.md' },
            { text: '九、调试优化', link: 'css09.md' },
          ],
        },
        {
          text: 'SASS 笔记',
          prefix: 'scss/',
          collapsible: true,
          children: [
            { text: '一、Sass简介', link: 'scss01.md' },
            { text: '二、基础知识', link: 'scss02.md' },
            { text: '三、进阶知识', link: 'scss03.md' },
            { text: '四、高级技巧', link: 'scss04.md' },
            { text: '五、最佳实践', link: 'scss05.md' },
          ],
        },

        {
          text: 'JS 笔记',
          prefix: 'js/',
          collapsible: true,
          children: [
            { text: '一、JS简介', link: 'js01.md' },
            { text: '二、基础知识', link: 'js02.md' },
            { text: '三、进阶知识', link: 'js03.md' },
            { text: '四、JS对象', link: 'js04.md' },
            { text: '五、DOM操作', link: 'js05.md' },
            { text: '六、BOM操作', link: 'js06.md' },
            { text: '七、调试技巧', link: 'js07.md' },
          ],
        },
        {
          text: 'ES6 笔记',
          prefix: 'es6/',
          collapsible: true,
          children: [
            { text: '一、ES6简介', link: 'es01.md' },
            { text: '二、声明变量', link: 'es02.md' },
            { text: '三、解构赋值', link: 'es03.md' },
            { text: '四、字符串扩展', link: 'es04.md' },
            { text: '五、函数扩展', link: 'es05.md' },
            { text: '六、数组扩展', link: 'es06.md' },
            { text: '七、对象扩展', link: 'es07.md' },
            { text: '八、新数据结构', link: 'es08.md' },
            { text: '九、异步编程', link: 'es09.md' },
            { text: '十、Class类', link: 'es10.md' },
            { text: '十一、模块化', link: 'es11.md' },
          ],
        },
        {
          text: 'TS 笔记',
          prefix: 'ts/',
          collapsible: true,
          children: [
            { text: '一、TS简介', link: 'ts01.md' },
            { text: '二、类型检测', link: 'ts02.md' },
            { text: '三、基本使用', link: 'ts03.md' },
            { text: '四、高级用法', link: 'ts04.md' },
          ],
        },
        {
          text: 'Vue2 笔记',
          prefix: 'vue/',
          collapsible: true,
          children: [
            { text: '一、Vue2简介', link: 'vue01.md' },
            { text: '二、基础知识', link: 'vue02.md' },
            { text: '三、指令', link: 'vue03.md' },
            { text: '四、VueCLI', link: 'vue04.md' },
            { text: '五、组件', link: 'vue05.md' },
            { text: '六、进阶主题', link: 'vue06.md' },
            { text: '七、路由', link: 'vue07.md' },
            { text: '八、状态', link: 'vue08.md' },
            { text: '九、生态系统', link: 'vue09.md' },
          ],
        },
        {
          text: 'Vue3 笔记',
          prefix: 'vue3/',
          collapsible: true,
          children: [
            { text: '一、Vue3简介', link: 'vueo01.md' },
            { text: '二、安装配置', link: 'vueo02.md' },
            { text: '三、基本语法', link: 'vueo03.md' },
            { text: '四、组件开发', link: 'vueo04.md' },
            { text: '五、路由导航', link: 'vueo05.md' },
            { text: '六、状态管理', link: 'vueo06.md' },
            { text: '七、状态管理', link: 'vueo07.md' },
            { text: '八、性能调优', link: 'vueo08.md' },
          ],
        },
        {
          text: '参照表',
          prefix: 'table/',
          collapsible: true,
          children: [
            { text: 'ASCLL', link: 'ascll.md' },
            { text: 'DOS', link: 'dos.md' },
            { text: 'HTTP', link: 'http.md' },
            { text: 'Regex', link: 'table.md' },
          ],
        },
      ],
    },
  ],
  '/md/backend': [
    '',
    {
      text: '后端',
      children: [
        {
          text: 'Java 笔记',
          prefix: 'java/',
          collapsible: true,
          children: [
            { text: '一、Java简介', link: 'java01.md' },
            { text: '二、基础知识', link: 'java02.md' },
            { text: '三、面向对象编程', link: 'java03.md' },
            { text: '四、进阶知识', link: 'java04.md' },
            { text: '五、标准库', link: 'java05.md' },
          ],
        },
        {
          text: 'JavaWeb 笔记',
          prefix: 'javaweb/',
          collapsible: true,
          children: [
            { text: '一、JavaWeb简介', link: 'javaweb01.md' },
            { text: '二、基础知识', link: 'javaweb02.md' },
            { text: '三、模板引擎', link: 'javaweb03.md' },
            { text: '四、MVC开发', link: 'javaweb04.md' },
            { text: '五、数据库操作', link: 'javaweb05.md' },
            { text: '六、权限安全', link: 'javaweb06.md' },
            // { text: '七、', link: 'javaweb07.md' },
            // { text: '八、', link: 'javaweb08.md' },
            // { text: '九、', link: 'javaweb09.md' },
          ],
        },
        {
          text: 'Spring 笔记',
          prefix: 'spring/',
          collapsible: true,
          children: [
            { text: '一、Spring简介', link: 'spring01.md' },
            { text: '二、IoC容器', link: 'spring02.md' },
            { text: '三、依赖注入', link: 'spring03.md' },
            { text: '四、AOP编程', link: 'spring04.md' },
            { text: '五、SpringEL', link: 'spring05.md' },
            { text: '六、高级特性', link: 'spring06.md' },
            // { text: '七、', link: 'spring07.md' },
            // { text: '八、', link: 'spring08.md' },
            // { text: '九、', link: 'spring09.md' },
          ],
        },
        {
          text: 'SpringMVC 笔记',
          prefix: 'springmvc/',
          collapsible: true,
          children: [
            { text: '一、SpringMVC简介', link: 'springmvc01.md' },
            { text: '二、MVC架构', link: 'springmvc02.md' },
            { text: '三、控制器', link: 'springmvc03.md' },
            { text: '四、视图解析器', link: 'springmvc04.md' },
            { text: '五、数据处理', link: 'springmvc05.md' },
            { text: '六、拦截器', link: 'springmvc06.md' },
            { text: '七、文件上传下载', link: 'springmvc07.md' },
            // { text: '八、', link: 'springmvc08.md' },
            // { text: '九、', link: 'springmvc09.md' },
          ],
        },
        {
          text: 'Mybatis 笔记',
          prefix: 'mybatis/',
          collapsible: true,
          children: [
            { text: '一、MyBatis简介', link: 'mybatis01.md' },
            { text: '二、入门指南', link: 'mybatis02.md' },
            { text: '三、数据查询', link: 'mybatis03.md' },
            { text: '四、动态SQL', link: 'mybatis04.md' },
            { text: '五、数据缓存', link: 'mybatis05.md' },
            { text: '六、高级特性', link: 'mybatis06.md' },
            // { text: '七、', link: 'mybatis07.md' },
            // { text: '八、', link: 'mybatis08.md' },
            // { text: '九、', link: 'mybatis09.md' },
          ],
        },
        // {
        //   text: 'SpringBoot',
        //   prefix: 'spring/',
        //   collapsible: true,
        //   children: [
        // { text: '一、', link: 'springboot01.md' },
        // { text: '二、', link: 'springboot02.md' },
        // { text: '三、', link: 'springboot03.md' },
        // { text: '四、', link: 'springboot04.md' },
        // { text: '五、', link: 'springboot05.md' },
        // { text: '六、', link: 'springboot06.md' },
        // { text: '七、', link: 'springboot07.md' },
        // { text: '八、', link: 'springboot08.md' },
        // { text: '九、', link: 'springboot09.md' },
        //   ],
        // },
        {
          text: 'Python 笔记',
          prefix: 'python/',
          collapsible: true,
          children: [
            { text: '一、Python 简介', link: 'python01.md' },
            { text: '二、基础语法', link: 'python02.md' },
            { text: '三、面向对象编程', link: 'python03.md' },
            { text: '四、标准库', link: 'python04.md' },
            { text: '五、高级特性', link: 'python05.md' },
            { text: '六、模块与异常', link: 'python06.md' },
            { text: '七、函数式编程', link: 'python07.md' },
            // { text: '八、', link: 'python08.md' },
            // { text: '九、', link: 'python09.md' },
          ],
        },
        {
          text: 'C 语言笔记',
          link: 'c/',
          prefix: 'c/',
          collapsible: true,
          children: [
            { text: '一、C语言介绍', link: 'c01.md' },
            { text: '二、基本语法', link: 'c02.md' },
            { text: '三、数据类型', link: 'c03.md' },
            { text: '四、运算符', link: 'c04.md' },
            { text: '五、控制语句', link: 'c05.md' },
            { text: '六、函数', link: 'c06.md' },
            { text: '七、字符串和数组', link: 'c07.md' },
            { text: '八、指针', link: 'c08.md' },
            { text: '九、结构体', link: 'c09.md' },
            { text: '十、联合体和枚举', link: 'c10.md' },
            { text: '十一、文件操作', link: 'c11.md' },
          ],
        },
        {
          text: 'Rust 笔记',
          link: 'rust/',
          prefix: 'rust/',
          collapsible: true,
          children: [
            { text: '一、Rust简介', link: 'rust01.md' },
            { text: '二、铺垫知识', link: 'rust02.md' },
            { text: '三、基础知识', link: 'rust03.md' },
            // { text: '四、', link: 'rust04.md' },
            // { text: '五、', link: 'rust05.md' },
            // { text: '六、', link: 'rust06.md' },
            // { text: '七、', link: 'rust07.md' },
            // { text: '八、', link: 'rust08.md' },
            // { text: '九、', link: 'rust09.md' },
          ],
        },
        {
          text: 'Mysql 笔记',
          prefix: 'mysql/',
          collapsible: true,
          children: [
            { text: '一、MySQL简介', link: 'mysql01.md' },
            { text: '二、安装配置', link: 'mysql02.md' },
            { text: '三、SQL语句', link: 'mysql03.md' },
            { text: '四、字段约束', link: 'mysql04.md' },
            { text: '五、事务简介', link: 'mysql05.md' },
            { text: '六、MySQL 函数', link: 'mysql06.md' },
            // { text: '七、', link: 'mysql07.md' },
            // { text: '八、', link: 'mysql08.md' },
            // { text: '九、', link: 'mysql09.md' },
          ],
        },
        {
          text: 'SQL 笔记',
          prefix: 'sql/',
          collapsible: true,
          children: [
            { text: '一、SQL简介', link: 'sql01.md' },
            { text: '二、数据类型', link: 'sql02.md' },
            { text: '三、数据定义', link: 'sql03.md' },
            { text: '四、数据控制', link: 'sql04.md' },
            { text: '五、数据操作', link: 'sql05.md' },
            { text: '六、数据查询', link: 'sql06.md' },
            // { text: '七、', link: 'sql07.md' },
            // { text: '八、', link: 'sql08.md' },
            // { text: '九、', link: 'sql09.md' },
          ],
        },
      ],
    },
  ],
  '/md/tools/': [
    '',
    {
      text: '工具',
      children: [
        {
          text: 'Linux 笔记',
          prefix: 'linux/',
          collapsible: true,
          children: [
            { text: '一、Linux简介', link: 'linux01.md' },
            { text: '二、接口管理', link: 'linux02.md' },
            { text: '三、文件系统', link: 'linux03.md' },
            { text: '四、常用命令', link: 'linux04.md' },
            { text: '五、常用软件', link: 'linux05.md' },
            { text: '六、进程管理', link: 'linux06.md' },
            { text: '七、管理维护', link: 'linux07.md' },
            { text: '八、网络配置', link: 'linux08.md' },
            { text: '九、服务器搭建', link: 'linux09.md' },
          ],
        },
        {
          text: 'Shell 笔记',
          prefix: 'shell/',
          collapsible: true,
          children: [
            { text: '一、Shell简介', link: 'shell01.md' },
            { text: '二、基本知识', link: 'shell02.md' },
            { text: '三、字符串和数组', link: 'shell03.md' },
            { text: '四、控制语句', link: 'shell04.md' },
            { text: '五、脚本编写', link: 'shell05.md' },
            { text: '六、高级主题', link: 'shell06.md' },
            // { text: '七、', link: 'shell07.md' },
            // { text: '八、', link: 'shell08.md' },
            // { text: '九、', link: 'shell09.md' },
          ],
        },
        {
          text: 'Vim 笔记',
          prefix: 'vim/',
          collapsible: true,
          children: [
            { text: '一、 vim介绍', link: 'vim01.md' },
            { text: '二、基本使用', link: 'vim02.md' },
            { text: '三、编辑模式', link: 'vim03.md' },
            // { text: '四、', link: 'vim04.md' },
            // { text: '五、', link: 'vim05.md' },
            // { text: '六、', link: 'vim06.md' },
            // { text: '七、', link: 'vim07.md' },
            // { text: '八、', link: 'vim08.md' },
            // { text: '九、', link: 'vim09.md' },
          ],
        },
        {
          text: 'Docker 笔记',
          prefix: 'docker/',
          collapsible: true,
          children: [
            { text: '一、Docker简介', link: 'docker01.md' },
            { text: '二、基本概念', link: 'docker02.md' },
            { text: '三、基本命令', link: 'docker03.md' },
            { text: '四、定制文件', link: 'docker04.md' },
            // { text: '五、', link: 'docker05.md' },
            // { text: '六、', link: 'docker06.md' },
            // { text: '七、', link: 'docker07.md' },
            // { text: '八、', link: 'docker08.md' },
            // { text: '九、', link: 'docker09.md' },
          ],
        },
        {
          text: 'Nginx 笔记',
          prefix: 'nginx/',
          collapsible: true,
          children: [
            { text: '一、Nginx简介', link: 'nginx01.md' },
            { text: '二、入门指南', link: 'nginx02.md' },
            { text: '三、基础实战', link: 'nginx03.md' },
            // { text: '四、', link: 'nginx04.md' },
            // { text: '五、', link: 'nginx05.md' },
            // { text: '六、', link: 'nginx06.md' },
            // { text: '七、', link: 'nginx07.md' },
            // { text: '八、', link: 'nginx08.md' },
            // { text: '九、', link: 'nginx09.md' },
          ],
        },
        {
          text: 'Git 笔记',
          collapsible: true,
          prefix: 'git/',
          children: [
            { text: '一、版本控制', link: 'git01.md' },
            { text: '二、环境配置', link: 'git02.md' },
            { text: '三、基本理论', link: 'git03.md' },
            { text: '四、项目搭建', link: 'git04.md' },
            { text: '五、文件操作', link: 'git05.md' },
            { text: '六、 GIT分支', link: 'git06.md' },
            // { text: '七、', link: 'git07.md' },
            // { text: '八、', link: 'git08.md' },
            // { text: '九、', link: 'git09.md' },
          ],
        },
        {
          text: 'Regex 笔记',
          collapsible: true,
          prefix: 'regex/',
          children: [
            { text: '一、', link: 'regex01.md' },
            // { text: '二、', link: 'regex02.md' },
            // { text: '三、', link: 'regex03.md' },
            // { text: '四、', link: 'regex04.md' },
            // { text: '五、', link: 'regex05.md' },
            // { text: '六、', link: 'regex06.md' },
            // { text: '七、', link: 'regex07.md' },
            // { text: '八、', link: 'regex08.md' },
            // { text: '九、', link: 'regex09.md' },
          ],
        },
      ],
    },
  ],
  '/md/ai/': [
    '',
    {
      text: '人工智能',
      children: [
        {
          text: 'Numpy 笔记',
          collapsible: true,
          prefix: 'numpy/',
          children: [
            { text: '一、NumPy简介', link: 'numpy01.md' },
            { text: '二、基本操作', link: 'numpy02.md' },
            { text: '三、数据类型', link: 'numpy03.md' },
            { text: '四、数组运算', link: 'numpy04.md' },
            { text: '五、复制和视图', link: 'numpy05.md' },
            { text: '六、高级特性', link: 'numpy06.md' },
            { text: '七、形状操作', link: 'numpy07.md' },
            { text: '八、广播机制', link: 'numpy08.md' },
            { text: '九、通用函数', link: 'numpy09.md' },
            { text: '十、线性代数', link: 'numpy10.md' },
          ],
        },
        {
          text: 'Pandas 笔记',
          collapsible: true,
          prefix: 'pandas/',
          children: [
            { text: '一、pandas介绍', link: 'pandas01.md' },
            { text: '二、数据结构', link: 'pandas02.md' },
            { text: '三、数据查看', link: 'pandas03.md' },
            { text: '四、输入输出', link: 'pandas04.md' },
            { text: '五、数据选取', link: 'pandas05.md' },
            { text: '六、数据集成', link: 'pandas06.md' },
            { text: '七、数据清洗', link: 'pandas07.md' },
            { text: '八、数据转换', link: 'pandas08.md' },
            { text: '九、数据重塑', link: 'pandas09.md' },
            { text: '十、统计方法', link: 'pandas10.md' },
            { text: '十一、数据排序', link: 'pandas11.md' },
            { text: '十二、分箱操作', link: 'pandas12.md' },
            { text: '十三、分组聚合', link: 'pandas13.md' },
            { text: '十四、时间序列', link: 'pandas14.md' },
            { text: '十五、数据可视化', link: 'pandas15.md' },
            { text: '十六、项目实战', link: 'pandas16.md' },
          ],
        },
        {
          text: 'Matplotlib 笔记',
          collapsible: true,
          prefix: 'matplotlib/',
          children: [
            { text: '一、Matplotlib简介', link: 'matplotlib01.md' },
            { text: '二、基础知识', link: 'matplotlib02.md' },
            { text: '三、风格样式', link: 'matplotlib03.md' },
            { text: '四、多图布局', link: 'matplotlib04.md' },
            { text: '五、基本样式', link: 'matplotlib05.md' },
            { text: '六、常用视图', link: 'matplotlib06.md' },
            { text: '七、3D图形', link: 'matplotlib07.md' },
            // { text: '八、', link: 'matplotlib08.md' },
            // { text: '九、', link: 'matplotlib09.md' },
          ],
        },
        {
          text: 'OpenCV 笔记',
          collapsible: true,
          prefix: 'opencv/',
          children: [
            { text: '一、OpenCV简介', link: 'opencv01.md' },
            { text: '二、图像处理基础', link: 'opencv02.md' },
            { text: '三、特征检测与描述', link: 'opencv03.md' },
            { text: '四、目标检测与识别', link: 'opencv04.md' },
            { text: '五、图像分割与轮廓提取', link: 'opencv05.md' },
            { text: '六、图像配准与拼接', link: 'opencv06.md' },
            { text: '七、视频处理', link: 'opencv07.md' },
            { text: '八、实时图像处理', link: 'opencv08.md' },
            { text: '九、图像处理应用案例', link: 'opencv09.md' },
            { text: '九、高级主题', link: 'opencv10.md' },
          ],
        },
      ],
    },
  ],
  '/ungee/408/': [
    '',
    {
      text: '408',
      children: [
        {
          text: '数据',
          prefix: 'ds',
          collapsible: true,
          children: [
            { text: '一、简介', link: 'ds01.md' },
            { text: '二、算法复杂度分析', link: 'ds02.md' },
            { text: '三、线性数据结构', link: 'ds03.md' },
            { text: '四、树形数据结构', link: 'ds04.md' },
            { text: '五、图形数据结构', link: 'ds05.md' },
            { text: '六、散列数据结构', link: 'ds06.md' },
            { text: '七、高级数据结构', link: 'ds07.md' },
            // { text: '八、', link: 'ds08.md' },
            // { text: '九、', link: 'ds09.md' },
          ],
        },
        {
          text: '计组',
          prefix: 'co',
          collapsible: true,
          children: [
            { text: '一、引言', link: 'co01.md' },
            { text: '二、数字逻辑与数字系统', link: 'co02.md' },
            { text: '三、指令系统', link: 'co03.md' },
            { text: '四、中央处理器', link: 'co04.md' },
            { text: '五、存储器层次结构', link: 'co05.md' },
            { text: '六、输入输出系统', link: 'co06.md' },
            { text: '七、总线系统', link: 'co07.md' },
            { text: '八、计算机性能评价', link: 'co08.md' },
            // { text: '九、', link: 'co09.md' },
          ],
        },
        {
          text: '系统',
          prefix: 'os',
          collapsible: true,
          children: [
            { text: '一、操作系统概述', link: 'os01.md' },
            { text: '二、进程管理', link: 'os02.md' },
            { text: '三、内存管理', link: 'os03.md' },
            { text: '四、文件系统', link: 'os04.md' },
            { text: '五、输入输出系统', link: 'os05.md' },
            { text: '六、死锁', link: 'os06.md' },
            // { text: '七、', link: 'os07.md' },
            // { text: '八、', link: 'os08.md' },
            // { text: '九、', link: 'os09.md' },
          ],
        },
        {
          text: '计网',
          prefix: 'cn',
          collapsible: true,
          children: [
            { text: '一、网络基础', link: 'cn01.md' },
            { text: '二、物理层', link: 'cn02.md' },
            { text: '三、数据链路层', link: 'cn03.md' },
            { text: '四、网络层', link: 'cn04.md' },
            { text: '五、传输层', link: 'cn05.md' },
            { text: '六、应用层', link: 'cn06.md' },
            { text: '七、网络安全', link: 'cn07.md' },
            { text: '八、无线与移动网络', link: 'cn08.md' },
            { text: '九、互联网与下一代网络', link: 'cn09.md' },
          ],
        },
        {
          text: '算法',
          prefix: 'al',
          collapsible: true,
          children: [
            { text: '一、算法基础', link: 'al01.md' },
            { text: '二、基本算法思想', link: 'al02.md' },
            { text: '三、排序算法', link: 'al03.md' },
            { text: '四、搜索算法', link: 'al04.md' },
            { text: '五、字符串匹配算法', link: 'al05.md' },
            // { text: '六、', link: 'al06.md' },
            // { text: '七、', link: 'al07.md' },
            // { text: '八、', link: 'al08.md' },
            // { text: '九、', link: 'al09.md' },
          ],
        },
      ],
    },
  ],
  '/ungee/english/': [
    '',
    {
      text: '英语',
      children: [
        {
          text: '词汇',
          collapsible: true,
          prefix: 'word/',
          children: [
            { text: '一、', link: 'word01.md' },
            { text: '二、', link: 'word02.md' },
            { text: '三、', link: 'word03.md' },
            { text: '四、', link: 'word04.md' },
            { text: '五、', link: 'word05.md' },
            { text: '六、', link: 'word06.md' },
            { text: '七、', link: 'word07.md' },
            { text: '八、', link: 'word08.md' },
            { text: '九、', link: 'word09.md' },
          ],
        },
        {
          text: '阅读',
          prefix: 'read/',
          collapsible: true,
          children: [
            { text: '一、', link: 'read01.md' },
            { text: '二、', link: 'read02.md' },
            { text: '三、', link: 'read03.md' },
            { text: '四、', link: 'read04.md' },
            { text: '五、', link: 'read05.md' },
            { text: '六、', link: 'read06.md' },
            { text: '七、', link: 'read07.md' },
            { text: '八、', link: 'read08.md' },
            { text: '九、', link: 'read09.md' },
          ],
        },
        {
          text: '听力',
          prefix: 'listen/',
          collapsible: true,
          children: [
            { text: '一、', link: 'listen01.md' },
            { text: '二、', link: 'listen02.md' },
            { text: '三、', link: 'listen03.md' },
            { text: '四、', link: 'listen04.md' },
            { text: '五、', link: 'listen05.md' },
            { text: '六、', link: 'listen06.md' },
            { text: '七、', link: 'listen07.md' },
            { text: '八、', link: 'listen08.md' },
            { text: '九、', link: 'listen09.md' },
          ],
        },
        {
          text: '写作',
          prefix: 'write/',
          collapsible: true,
          children: [
            { text: '一、', link: 'write01.md' },
            { text: '二、', link: 'write02.md' },
            { text: '三、', link: 'write03.md' },
            { text: '四、', link: 'write04.md' },
            { text: '五、', link: 'write05.md' },
            { text: '六、', link: 'write06.md' },
            { text: '七、', link: 'write07.md' },
            { text: '八、', link: 'write08.md' },
            { text: '九、', link: 'write09.md' },
          ],
        },
        {
          text: '口语',
          prefix: 'speak/',
          collapsible: true,
          children: [
            { text: '一、', link: 'speak01.md' },
            { text: '二、', link: 'speak02.md' },
            { text: '三、', link: 'speak03.md' },
            { text: '四、', link: 'speak04.md' },
            { text: '五、', link: 'speak05.md' },
            { text: '六、', link: 'speak06.md' },
            { text: '七、', link: 'speak07.md' },
            { text: '八、', link: 'speak08.md' },
            { text: '九、', link: 'speak09.md' },
          ],
        },
        {
          text: '语法',
          prefix: 'grammar/',
          collapsible: true,
          children: [
            { text: '一、', link: 'grammar01.md' },
            { text: '二、', link: 'grammar02.md' },
            { text: '三、', link: 'grammar03.md' },
            { text: '四、', link: 'grammar04.md' },
            { text: '五、', link: 'grammar05.md' },
            { text: '六、', link: 'grammar06.md' },
            { text: '七、', link: 'grammar07.md' },
            { text: '八、', link: 'grammar08.md' },
            { text: '九、', link: 'grammar09.md' },
          ],
        },
        {
          text: '翻译',
          prefix: 'translate/',
          collapsible: true,
          children: [
            { text: '一、', link: 'translate01.md' },
            { text: '二、', link: 'translate02.md' },
            { text: '三、', link: 'translate03.md' },
            { text: '四、', link: 'translate04.md' },
            { text: '五、', link: 'translate05.md' },
            { text: '六、', link: 'translate06.md' },
            { text: '七、', link: 'translate07.md' },
            { text: '八、', link: 'translate08.md' },
            { text: '九、', link: 'translate09.md' },
          ],
        },
      ],
    },
  ],
  '/ungee/math/': [
    '',
    {
      text: '数学',
      children: [
        {
          text: '高数',
          prefix: 'calculus/',
          collapsible: true,
          children: [
            { text: '一、函数与极限', link: 'calculus01.md' },
            { text: '二、导数与微分', link: 'calculus02.md' },
            { text: '三、微分学应用', link: 'calculus03.md' },
            { text: '四、不定积分', link: 'calculus04.md' },
            { text: '五、定积分', link: 'calculus05.md' },
            { text: '六、微分方程', link: 'calculus06.md' },
            { text: '七、多元函数微分学', link: 'calculus07.md' },
            { text: '八、多重积分', link: 'calculus08.md' },
            { text: '九、曲线与曲面积分', link: 'calculus09.md' },
            { text: '十、无穷级数', link: 'calculus10.md' },
          ],
        },
        {
          text: '线代',
          prefix: 'algebra/',
          collapsible: true,
          children: [
            { text: '一、向量空间', link: 'algebra01.md' },
            { text: '二、矩阵与线性方程组', link: 'algebra02.md' },
            { text: '三、线性变换', link: 'algebra03.md' },
            { text: '四、特殊矩阵与特征值问题', link: 'algebra04.md' },
            { text: '五、内积空间与正交性', link: 'algebra05.md' },
            { text: '六、二次型与正定性', link: 'algebra06.md' },
            // { text: '七、', link: 'algebra07.md' },
            // { text: '八、', link: 'algebra08.md' },
            // { text: '九、', link: 'algebra09.md' },
          ],
        },
      ],
    },
  ],
  '/ungee/politics/': [
    '',
    {
      text: '政治',
      children: [
        {
          text: '马原',
          prefix: 'ma/',
          collapsible: true,
          children: [
            { text: '一、', link: 'ma01.md' },
            { text: '二、', link: 'ma02.md' },
            { text: '三、', link: 'ma03.md' },
            { text: '四、', link: 'ma04.md' },
            { text: '五、', link: 'ma05.md' },
            { text: '六、', link: 'ma06.md' },
            { text: '七、', link: 'ma07.md' },
            { text: '八、', link: 'ma08.md' },
            { text: '九、', link: 'ma09.md' },
          ],
        },
        {
          text: '毛中特',
          prefix: 'mao/',
          collapsible: true,
          children: [
            { text: '一、', link: 'mao01.md' },
            { text: '二、', link: 'mao02.md' },
            { text: '三、', link: 'mao03.md' },
            { text: '四、', link: 'mao04.md' },
            { text: '五、', link: 'mao05.md' },
            { text: '六、', link: 'mao06.md' },
            { text: '七、', link: 'mao07.md' },
            { text: '八、', link: 'mao08.md' },
            { text: '九、', link: 'mao09.md' },
          ],
        },
        {
          text: '新思想',
          prefix: 'xin/',
          collapsible: true,
          children: [
            { text: '一、', link: 'xin01.md' },
            { text: '二、', link: 'xin02.md' },
            { text: '三、', link: 'xin03.md' },
            { text: '四、', link: 'xin04.md' },
            { text: '五、', link: 'xin05.md' },
            { text: '六、', link: 'xin06.md' },
            { text: '七、', link: 'xin07.md' },
            { text: '八、', link: 'xin08.md' },
            { text: '九、', link: 'xin09.md' },
          ],
        },
        {
          text: '思修',
          prefix: 'si/',
          collapsible: true,
          children: [
            { text: '一、', link: 'si01.md' },
            { text: '二、', link: 'si02.md' },
            { text: '三、', link: 'si03.md' },
            { text: '四、', link: 'si04.md' },
            { text: '五、', link: 'si05.md' },
            { text: '六、', link: 'si06.md' },
            { text: '七、', link: 'si07.md' },
            { text: '八、', link: 'si08.md' },
            { text: '九、', link: 'si09.md' },
          ],
        },
        {
          text: '近代史',
          prefix: 'jin/',
          collapsible: true,
          children: [
            { text: '一、', link: 'jin01.md' },
            { text: '二、', link: 'jin02.md' },
            { text: '三、', link: 'jin03.md' },
            { text: '四、', link: 'jin04.md' },
            { text: '五、', link: 'jin05.md' },
            { text: '六、', link: 'jin06.md' },
            { text: '七、', link: 'jin07.md' },
            { text: '八、', link: 'jin08.md' },
            { text: '九、', link: 'jin09.md' },
          ],
        },
        {
          text: '时政',
          prefix: 'shi/',
          collapsible: true,
          children: [
            { text: '一、', link: 'shi01.md' },
            { text: '二、', link: 'shi02.md' },
            { text: '三、', link: 'shi03.md' },
            { text: '四、', link: 'shi04.md' },
            { text: '五、', link: 'shi05.md' },
            { text: '六、', link: 'shi06.md' },
            { text: '七、', link: 'shi07.md' },
            { text: '八、', link: 'shi08.md' },
            { text: '九、', link: 'shi09.md' },
          ],
        },
      ],
    },
  ],
  '/other/': [
    '',
    { text: '每周计划', link: 'task.md' },
    { text: '更新日志', link: 'log.md' },
    { text: '文档说明', link: 'explain.md' },
  ],
})
